### ISSUE TITLE
Package win64  Error

### ISSUE THREAD

**Issue by qipaworld** [jwindgassen/UnrealYAML#3]
blic\Node.h(182): error C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
UATHelper: Packaging (Windows (64-bit)):     [19/21]

**Comment by jwindgassen** [comment]
Can you still check if that error still occurs? I also stumbled around it at some point, but I think I already fixed it.

**Comment by gyrovague** [comment]
I actually get this too (using latest version of this plugin). It doesn't happen in Editor target builds, only Game (so far) for some reason. I guess maybe it's a problem that the exception code is in the Node.h header instead of the cpp, perhaps the exception "spreads" to the code it is used from (where bEnableExceptions is not true), though I'm not sure why it works fine in Editor builds in that case.

**Comment by jwindgassen** [comment]
@qipaworld @gyrovague Can you try to set `bEnableExceptions = true;` in the `Build.cs` of the project that uses the Plugin and see if the warning disappears?
I think since the Plugin uses try-catch-statements in the header files, modules using this Plugin will also need to enable Exception. This is a bit unfortunate, but I don't see a simple way to fix this.
If adding this line removes the error, I will add a note to the README.

**Comment by stayingcozy** [comment]
I had a similar issue that qipaworld and gyrovague had. Putting `bEnableExceptions = true;` in both `UnrealYAML.Build.cs` and my `<project_name>.Build.cs` allowed me to package Unreal correctly for windows.
